### PR TITLE
resolve #46: Example Project

### LINKED ISSUE #46: [FR]: example app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

We should create example project for easing of development or contribution.

### Describe the solution

I will refer [this project's settings](https://github.com/kanelloc/react-native-animated-header-scroll-view)

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mym0404**
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## What does this change?

Add example project

Fixes #46 🎯

### CODE REVIEW

**Comment by mym0404** [comment]
@zmin9 can you check the example project run correctly?

`yarn example ios`
`yarn example android`

**Comment by zmin9** [comment]
<details><summary>Each of these had issues, but they worked out well👍</summary>
<p>

In `yarn example ios`,
* Command failed: osascript -e tell app “System Events” to count processes whose name is “Simulator”
* resolved with turning on `System settings > Privacy & Security > Automation > WebStorm(or terminal?) - System Events`

In `yarn example android`
* Watchman error: std::__1::system_error: open: {PROJECT_PATH}: Operation not permitted
* resolved with `watchman watch-del-all && watchman shutdown-server` in cmd

</p>
</details> 

image

**Comment by mym0404** [comment]
Slick!

Can you append it to Example project running guide section in Contributing.md?

**Comment by mym0404** [comment]
I did

**Pull request merged**
